universe = vanilla
executable = /home/phil/Documents/Research/eos-inf/bin/collectbinaries
arguments = "$(outdir)"
output = /home/phil/Documents/Research/tmp/log/collectbinaries-$(job).out
error = /home/phil/Documents/Research/tmp/log/collectbinaries-$(job).err
log = /home/phil/Documents/Research/tmp/log/collectbinaries-$(job).log
getenv = True
accounting_group = ligo.dev.o2.cbc.pe.lalinference
accounting_group.user = philippe.landry
queue 1
