universe = vanilla
executable = /home/phil/Documents/Research/eos-inf/bin/draweos
arguments = "$(jobi)" "1" "$(perdir)" "$(gpfile)" "$(outdir)"
output = /home/phil/Documents/Research/tmp/log/draweos-$(job).out
error = /home/phil/Documents/Research/tmp/log/draweos-$(job).err
log = /home/phil/Documents/Research/tmp/log/draweos-$(job).log
getenv = True
accounting_group = ligo.dev.o2.cbc.pe.lalinference
accounting_group.user = philippe.landry
queue 1
