universe = vanilla
executable = /home/phil/Documents/Research/eos-inf/bin/getbinaries
arguments = "$(mpereos)" "$(outdir)"
output = /home/phil/Documents/Research/tmp/log/getbinaries-$(job).out
error = /home/phil/Documents/Research/tmp/log/getbinaries-$(job).err
log = /home/phil/Documents/Research/tmp/log/getbinaries-$(job).log
getenv = True
accounting_group = ligo.dev.o2.cbc.pe.lalinference
accounting_group.user = philippe.landry
queue 1
