universe = vanilla
executable = /home/phil/Documents/Research/eos-inf/bin/getprops
arguments = "$(job)" "$(perdir)" "$(outdir)"
output = /home/phil/Documents/Research/tmp/log/getprops-$(job).out
error = /home/phil/Documents/Research/tmp/log/getprops-$(job).err
log = /home/phil/Documents/Research/tmp/log/getprops-$(job).log
getenv = True
accounting_group = ligo.dev.o2.cbc.pe.lalinference
accounting_group.user = philippe.landry
queue 1
