universe = vanilla
executable = /home/phil/Documents/Research/eos-inf/bin/weighsamps
arguments = "$(gwfile)" "$(sampfile)" "$(weightsfile)" "$(outdir)"
output = /home/phil/Documents/Research/tmp/log/weighsamps-$(job).out
error = /home/phil/Documents/Research/tmp/log/weighsamps-$(job).err
log = /home/phil/Documents/Research/tmp/log/weighsamps-$(job).log
getenv = True
accounting_group = ligo.dev.o2.cbc.pe.lalinference
accounting_group.user = philippe.landry
queue 1
